### ISSUE TITLE
搜狗scel词库转成txt格式出现错误？

### ISSUE THREAD

**Issue by lemonhu** [WuLC/ThesaurusParser#1]
你好，首先谢谢你分享的词库解析程序，我在利用该程序解析  搜狗网络流行新词【官方推荐】.scel  这个词库时([该搜狗词库链接](http://pinyin.sogou.com/dict/detail/index/4))，出现如下错误：
`at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at edu.hzq.dic.SougouScelReader.read(SougouScelReader.java:20)
	at edu.hzq.dic.SogouScel2Txt.sogou(SogouScel2Txt.java:70)
	at edu.hzq.dic.SogouScel2Txt.main(SogouScel2Txt.java:40)`

**Comment by WuLC** [comment]
我这边出现的是 `EOFException`, 考虑到搜狗其他的词库文件都能正常解析，就不对其做特殊处理了，仅仅是捕获了这个异常然后将已经解析了的词语写入新的文件，代码能够正常跑，但是词库部分词条可能有丢失。这个问题可能是是由于这个词库文件的格式异常所致，我通过深蓝解析出来的词语是5524条，而代码跑出来的结果也是在解析到5525行抛出了这个exception。这是我目前想到最简单的方法，如有更好的解决方案，欢迎讨论

**Comment by lemonhu** [comment]
我也觉得这个词库的格式有些异常，其他词库解析都没问题，谢谢你的解答！

**Comment by li871804050** [comment]
貌似词库中的包含数字和字母的词语都没有解析出来
